# Author: Enrico Veraldi
# Core for the execution of CLOUDY runs for the galapy spectroscopy package

# Python standard library module that provides a high-level interface for asynchronously executing callables
# using pools of threads or processes
import concurrent.futures as _fut
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys
import time
# imports a tool that automatically sets up a class to store data, make possible immutable data (avoid runtime mod.)
from dataclasses import dataclass

from galapy.spectroscopy.utils import CLOUDY_REQUIRED, cloudy_banner, require_cloudy

# for wildcard import (public interface)
__all__ = ['Sector', 'SECTORS', 'CONVERGENCE_CAUTION', 'parse_index_selector',
           'read_manifest', 'sed_referenced_by', 'is_complete', 'converged_from_out',
           'stage_job', 'run_job', 'plan_jobs', 'run_all', 'build_parser', 'main']

# message for not reaching convergence in CLOUDY runs
CONVERGENCE_CAUTION = 'CLOUDY Iteration to convergence did not converge'

# freeze parameters at first initialization
# is the sector associated to runs
@dataclass(frozen=True)
class Sector:
    name: str           # 'hii' - 'pdr'
    saves: tuple        # saving files from deck cloudy inputs
    linelist: str       # file list from command 'save line list'
    parse_module: str   # parser per model

# SECTORS HII AND PDR METADATA
SECTORS = {
    'hii': Sector(
        name='hii',
        saves=('.con', '.con_grain', '.lines', '.dusa', '.grain_temp'),
        linelist='hii_lines.dat',
        parse_module='galapy.spectroscopy.utils.hii.parse_one'),
    'pdr': Sector(
        name='pdr',
        saves=('.con', '.con_grain', '.lines', '.dusa', '.pdr', '.heat', '.cool'),
        linelist='pdr_lines.dat',
        parse_module='galapy.spectroscopy.utils.pdr.parse_one'),
}

_SED_RE = re.compile(r'^\s*table\s+SED\s+"([^"]+)"', re.IGNORECASE | re.MULTILINE) #reg expression for SED name in cloudy deck

def sed_referenced_by(deck_text):
    """
    Return the SED name referenced by the given CLOUDY deck.
    """
    m = _SED_RE.search(deck_text)
    return None if m is None else os.path.basename(m.group(1))

_ABN_RE = re.compile(r'^\s*abun\w*\s+"([^"]+)"', re.IGNORECASE | re.MULTILINE)

def abn_referenced_by(deck_text):
    """
    Return the abundance file name referenced by the given CLOUDY deck.
    """
    m = _ABN_RE.search(deck_text)
    return None if m is None else os.path.basename(m.group(1))

def parse_index_selector(text):
    """
    Parses a string representing a series of numeric index selectors (manifest for the run
    of cloudy wanted by user) and returns a sorted list of unique integers. The input string
    can contain individual numbers or ranges of numbers separated by commas. Ranges should use
    a hyphen to denote start and end. Negative indexes and reversed intervals are not allowed.
    es. '0-9,20,30-32' -> [0..9, 20, 30, 31, 32]

    Raises:
        ValueError: If a range is reversed or if any negative index is provided.

    Args:
        text (str): The input string containing numeric index selectors or ranges.

    Returns:
        list[int]: A sorted list of unique integers parsed from the input string.
    """
    out = set()
    for chunk in str(text).split(','):
        chunk = chunk.strip()
        if not chunk:
            continue
        if '-' in chunk.lstrip('-'):
            a, b = chunk.split('-', 1)
            a, b = int(a), int(b)
            if b < a:
                raise ValueError(f"reversed interval: '{chunk}'")
            out.update(range(a, b + 1))
        else:
            out.add(int(chunk))
    if any(i < 0 for i in out):
        raise ValueError('negative indexes not allowed')
    return sorted(out)

def read_manifest(path):
    """
    Reads and validates a job manifest file (jobs.txt generated by gen_input_*.py),
    ensuring unique job IDs.

    Args:
        path (str): Path to the manifest file to be read.

    Returns:
        list[str]: A list of unique job IDs extracted from the manifest file.

    Raises:
        ValueError: If the manifest file is empty or contains duplicate job IDs.
    """
    lines = [ln.strip() for ln in pathlib.Path(path).read_text().splitlines()]
    ids = [ln for ln in lines if ln]
    if not ids:
        raise ValueError(f'no jobs in jobs.txt: {path}')
    if len(set(ids)) != len(ids):
        raise ValueError(f'job_id duplicated in {path}')
    return ids

def is_complete(workdir, sector, job_id):
    """
    Determines if a job is complete based on the presence of required save files
    and a final convergence flag file.

    A job is considered complete if:
    1. All necessary save files for the specified sector are present in the
       working directory.
    2. The `converged.flag` file is present, indicating that the run has
       successfully reached its end.

    Parameters:
    workdir: str
        The working directory where all files are expected to be located.
    sector: any
        An object representing the sector, which includes a `name` attribute
        and a `saves` list specifying the expected save file extensions.
    job_id: str
        A unique identifier for the job whose completeness is being checked.

    Returns:
    bool
        True if the job is complete, False otherwise.
    """
    wd = pathlib.Path(workdir)
    if not (wd / 'converged.flag').is_file():
        return False
    return all((wd / f'{sector.name}_{job_id}{ext}').is_file() for ext in sector.saves)

def converged_from_out(out_text):
    """
    True if the model is converged
    """
    return CONVERGENCE_CAUTION not in out_text

def stage_job(runs_dir, work_root, sector, job_id, linelist_dir=None):
    """
    Stages a job by preparing necessary input files and directories for processing.

    This function sets up the required workspace for a job by copying key input
    files, such as the input deck, SED files, ABD file, and line list files, into
    a designated working directory. It raises errors if any critical files are
    missing or cannot be accessed.

    Arguments:
        runs_dir (str or pathlib.Path): Path to the directory containing the
            input files and resources for jobs.
        work_root (str or pathlib.Path): Root directory where the working
            directory for the job will be created.
        sector (Sector): Sector instance containing job-specific metadata. It
            must include the name and linelist attributes.
        job_id (str): Unique identifier for the job.
        linelist_dir (str or pathlib.Path, optional): Path to the line list
            directory. If not provided, the environment variable
            'CLOUDIA_LINELISTS' will be used as fallback.

    Returns:
        tuple[pathlib.Path, pathlib.Path]: A tuple containing:
            - The path to the working directory where files are staged (pathlib.Path).
            - The path to the staged input deck file within the working directory (pathlib.Path).

    Raises:
        FileNotFoundError: If critical files such as the input deck, required SED, required ABD,
            or line list file are not available in their expected locations.
    """
    runs = pathlib.Path(runs_dir)
    deck_src = runs / f'{sector.name}_{job_id}.in'
    if not deck_src.is_file():
        raise FileNotFoundError(f'input deck absent: {deck_src} (have you run galapy-gen-hii/pdr?)')

    wd = pathlib.Path(work_root) / job_id
    wd.mkdir(parents=True, exist_ok=True)
    deck_dst = wd / deck_src.name
    shutil.copy2(deck_src, deck_dst)

    sed_name = sed_referenced_by(deck_dst.read_text())
    if sed_name:
        (wd / 'SED').mkdir(exist_ok=True)
        sed_src = runs / 'SED' / sed_name
        if not sed_src.is_file():
            raise FileNotFoundError(
                f"SED missing: {sed_src}.")
        shutil.copy2(sed_src, wd / 'SED' / sed_name)

    abn_name = abn_referenced_by(deck_dst.read_text())
    if abn_name:
        from galapy.internal.data import DataFile
        from galapy.internal import globs as GLOBS
        abn_src = pathlib.Path(DataFile(abn_name, GLOBS.ABU_DIR).get_file())
        if not abn_src.is_file():
            raise FileNotFoundError(f'abundance file absent: {abn_src}')
        shutil.copy2(abn_src, wd / abn_name)

    ll_dir = linelist_dir or os.environ.get('CLOUDIA_LINELISTS')
    if ll_dir:
        ll_src = pathlib.Path(ll_dir) / sector.linelist
        if not ll_src.is_file():
            raise FileNotFoundError(
                f'line list file absent: {ll_src}.')
        shutil.copy2(ll_src, wd / sector.linelist)

    return wd, deck_dst

def run_job(job_id, runs_dir, work_root, sector_name, exe, timeout,
            linelist_dir=None, resume=False, parse=False):
    """
    Runs a CLOUDY job based on the provided parameters and captures the results, including status,
    execution time, and convergence information.

    Parameters:
        job_id (str): Unique identifier for the job.
        runs_dir (str): Directory containing previously executed runs.
        work_root (str): Root directory where jobs will be executed.
        sector_name (str): Name of the sector related to the job, used for job configuration.
        exe (str): Path to the external executable to be run (CLOUDY executable)
        timeout (float): Maximum time, in seconds, allowed for the job to execute.
        linelist_dir (Optional[str]): Directory containing line lists for the job. Defaults to None.
        resume (bool): Flag indicating whether execution should resume from an existing incomplete job. Defaults to False.
        parse (bool): Option to enable parsing features for the job. Defaults to False.

    Returns:
        dict: A dictionary containing the keys:
            - job_id (str): The unique identifier for the job.
            - status (str): Status of the job ('ok', 'failed', 'skipped', or 'timeout').
            - converged (bool or None): Whether the job converged or None if skipped.
            - returncode (int or None): The return code from the external executable, or None if skipped.
            - missing (list): List of missing files based on sector requirements.
            - seconds (float): Total time taken for the job to execute.
            - workdir (str): Path to the working directory where the job was executed.

    Raises:
        subprocess.TimeoutExpired: Raised when the execution takes longer than the specified timeout.
    """
    sector = SECTORS[sector_name]
    t0 = time.time()
    wd = pathlib.Path(work_root) / job_id
    if resume and is_complete(wd, sector, job_id):
        return {'job_id': job_id, 'status': 'skipped', 'converged': None,
                'seconds': 0.0, 'workdir': str(wd)}

    wd, _ = stage_job(runs_dir, work_root, sector, job_id, linelist_dir)
    prefix = f'{sector.name}_{job_id}'

    # cloudy -p <prefix>
    try:
        proc = subprocess.run([exe, '-p', prefix], cwd=str(wd), capture_output=True,
                              text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        (wd / 'TIMEOUT').write_text(f'timeout dopo {timeout} s\n')
        return {'job_id': job_id, 'status': 'timeout', 'converged': False,
                'seconds': time.time() - t0, 'workdir': str(wd)}

    out_path = wd / f'{prefix}.out'
    out_text = out_path.read_text(errors='replace') if out_path.is_file() else proc.stdout

    # CONVERGED?
    converged = converged_from_out(out_text)
    if not converged:
        (wd / 'NOT_CONVERGED').write_text('')

    missing = [ext for ext in sector.saves if not (wd / f'{prefix}{ext}').is_file()]
    status = 'ok' if (proc.returncode == 0 and not missing) else 'failed'

    (wd / 'converged.flag').write_text('1\n' if converged else '0\n')

    return {'job_id': job_id, 'status': status, 'converged': converged,
            'returncode': proc.returncode, 'missing': missing,
            'seconds': time.time() - t0, 'workdir': str(wd)}

def plan_jobs(manifest_ids, index_sel=None, job_ids=None):
    """
    Plans and filters jobs from a provided list of manifest IDs based on specified criteria.

    Args:
        manifest_ids (list[str]): A list of job identifiers from which jobs are selected.
        index_sel (str | None): An index selector string specifying job indices to select from
            the manifest. Treated as None if not passed.
        job_ids (list[str] | None): A list of job IDs to filter from the manifest. Treated as
            None if not passed.

    Raises:
        ValueError: If both `index_sel` and `job_ids` are provided, as they are mutually exclusive.
        KeyError: If any of the `job_ids` are not present in the `manifest_ids`.
        IndexError: If the indices specified in `index_sel` exceed the range of available
            `manifest_ids`.

    Returns:
        list[str]: A filtered list of job IDs based on the specified criteria. It corresponds
            to either the specified `job_ids` or indices from the manifest.
    """
    if index_sel and job_ids:
        raise ValueError('--index and --job-id are mutually exclusive')
    if job_ids:
        unknown = [j for j in job_ids if j not in set(manifest_ids)]
        if unknown:
            raise KeyError(f'job_id out from the jobs.txt deck: {unknown[:5]}')
        order = {j: k for k, j in enumerate(manifest_ids)}
        return sorted(set(job_ids), key=order.__getitem__)
    if index_sel is None:
        return list(manifest_ids)
    idx = parse_index_selector(index_sel)
    over = [i for i in idx if i >= len(manifest_ids)]
    if over:
        raise IndexError(f'index out of deck range: ({len(manifest_ids)} job): {over[:5]}')
    return [manifest_ids[i] for i in idx]

def run_all(jobs, runs_dir, work_root, sector_name, exe, timeout, nproc=1,
            linelist_dir=None, resume=False, on_result=None):
    """
    Executes jobs in either single process or pool mode and returns the list of outcomes.

    The function can run in single-process mode for debugging purposes or use
    a process pool for parallel execution when `nproc > 1`. In single-process
    mode, tracebacks are preserved for easier debugging.

    Parameters:
        jobs (list): A list of job configurations. Each job is a dictionary
            containing the necessary parameters for execution.
        runs_dir (str): Directory path where the job runtime results should be stored.
        work_root (str): Root directory for job execution.
        sector_name (str): Name of the sector the jobs are associated with.
        exe (str): Path to the executable to be used for job execution.
        timeout (int | float): Maximum allowed execution time for each job, in seconds.
        nproc (int, optional): Number of processes to use for execution. Defaults to 1.
        linelist_dir (str, optional): Directory containing additional data for specific job
            execution, if required.
        resume (bool, optional): Whether to resume execution if it was interrupted.
            Defaults to False.
        on_result (callable, optional): A callback function that will be invoked with the
            result of each completed job.

    Returns:
        list: A list of job execution results. Each result is a dictionary containing
            the job id and the corresponding outcome.
    """
    results = []
    #serial mode
    if nproc <= 1:
        for j in jobs:
            r = run_job(j, runs_dir, work_root, sector_name, exe, timeout,
                        linelist_dir, resume)
            results.append(r)
            if on_result: #functions for manage results on real-time when finished (increase the multitask)
                on_result(r)
        return results

    #parallel mode on CPU
    with _fut.ProcessPoolExecutor(max_workers=nproc) as pool: # initialise pool
        futs = {pool.submit(run_job, j, runs_dir, work_root, sector_name, exe,
                            timeout, linelist_dir, resume): j for j in jobs} #submit jobs
        for f in _fut.as_completed(futs):
            r = f.result()
            results.append(r)
            if on_result:
                on_result(r)
    order = {j: k for k, j in enumerate(jobs)}
    results.sort(key=lambda r: order[r['job_id']])
    return results

def write_run_manifest(path, sector_name, inst, results, extra=None):
    """
    Writes a run manifest summarizing execution provenance and job outcomes.

    This function creates a manifest file that contains metadata about the
    execution.

    Parameters:
    path: str
        The file path where the manifest will be saved.
    sector_name: str
        The name of the sector being processed.
    inst: object
        An instance containing attributes such as the executable path, version,
        and data path used during execution.
    results: list[dict]
        A list of job result dictionaries, each containing details such as
        status and convergence information for a specific job.
    extra: dict, optional
        Additional key-value pairs to include in the manifest, if any.

    Returns:
    dict
        The manifest data written to the specified file.
    """
    """Provenance del LANCIO, non del singolo job: un file, non 432000.

    Contiene il banner della versione EFFETTIVAMENTE eseguita — la sola prova
    di quale binario ha prodotto quei numeri (Decisione 8).
    """
    doc = {
        'sector': sector_name,
        'cloudy_exe': inst.exe,
        'cloudy_banner': inst.version,
        'cloudy_required': CLOUDY_REQUIRED,
        'cloudy_data_path': inst.data_path,
        'host': os.uname().nodename if hasattr(os, 'uname') else None,
        'timestamp_utc': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
        'n_jobs': len(results),
        'n_ok': sum(r['status'] == 'ok' for r in results),
        'n_skipped': sum(r['status'] == 'skipped' for r in results),
        'n_failed': sum(r['status'] in ('failed', 'timeout') for r in results),
        'n_not_converged': sum(r['converged'] is False for r in results),
        'jobs': results,
    }
    if extra:
        doc.update(extra)
    pathlib.Path(path).write_text(json.dumps(doc, indent=2))
    return doc

def build_parser(sector_name):
    """Il parser vive in una funzione, non al top level (T-0.8)."""
    import argparse
    s = sector_name
    ap = argparse.ArgumentParser(
        prog=f'galapy-run-cloudy-{s}',
        description=f'Execute the CLOUDY models for sector {s}.')
    ap.add_argument('-r','--runs', required=True,
                    help='deck directory produced by galapy-gen-* (should have SED/ and jobs.txt) suggested: data/[hii/pdr]')
    ap.add_argument('-w','--work', default=None,
                    help='workdir (default: <runs>/work)')
    ap.add_argument('-m','--manifest', default=None,
                    help='manifest  (default: <runs>/jobs.txt)')
    sel = ap.add_mutually_exclusive_group()
    sel.add_argument('-i','--index', default=None,
                     help="INDEX selection from the manifest, es. '0-49' o '0,7,12-15'. ")
    sel.add_argument('--job-id', nargs='+', default=None,
                     help='job_id explicit (mainly debug single model)')
    ap.add_argument('-j','--jobs', type=int, default=1,
                    help='parallel processes (default 1: with full traceback)')
    ap.add_argument('-t','--timeout', type=int, default=7200,
                    help='timeout for model in seconds (default 7200=2h)')
    ap.add_argument('-l','--linelists', default=None,
                    help='line list directory for `save line list` (default: $CLOUDIA_LINELISTS)')
    ap.add_argument('--resume', action='store_true',
                    help='skipp already completed jobs')
    ap.add_argument('-d','--dry-run', action='store_true',
                    help='print only run plan without running it')
    ap.add_argument('--report', default=None,
                    help='where writing the run plan (default: <work>/run_manifest.json)')
    ap.add_argument('--no-version-check', action='store_true',
                    help='do not check version banner. Only for development: a grid produced this way is not '
                         'commensurable with others.')
    return ap

def main(argv=None, sector_name='hii'):
    #SETTING (PARSER, DRY RUN...)
    ap = build_parser(sector_name)
    args = ap.parse_args(argv)

    runs = pathlib.Path(args.runs)
    work = pathlib.Path(args.work) if args.work else runs / 'work'
    manifest = pathlib.Path(args.manifest) if args.manifest else runs / f'jobs_{sector_name}.txt'

    try:
        ids = read_manifest(manifest)
        jobs = plan_jobs(ids, args.index, args.job_id)
    except (OSError, ValueError, KeyError, IndexError) as exc:
        print(f'[ERROR]: {exc}', file=sys.stderr)
        return 2

    if args.dry_run:
        print(f'[{sector_name}] {len(jobs)} job to execute; work={work}')
        for j in jobs[:20]:
            print(f'  {j}')
        if len(jobs) > 20:
            print(f'  ... and others {len(jobs) - 20}')
        return 0

    #CHECK
    from galapy.spectroscopy.utils import CloudyNotFound
    try:
        inst = require_cloudy(check_version=not args.no_version_check)
    except CloudyNotFound as exc:
        print(f'[ERROR]: {exc}', file=sys.stderr)
        return 1
    if inst.version is None:
        inst = inst._replace(version=cloudy_banner(inst.exe))

    work.mkdir(parents=True, exist_ok=True)
    print(f'[{sector_name}] CLOUDY: {inst.version or "(banner not read)"} — {inst.exe}',
          file=sys.stderr)
    print(f'[{sector_name}] {len(jobs)} job, {args.jobs} processes, work={work}',
          file=sys.stderr)

    def _echo(r):
        mark = {'ok': ' ', 'skipped': '-', 'failed': '!', 'timeout': 'T'}[r['status']]
        conv = '' if r['converged'] is not False else '  [NOT CONVERGED]'
        print(f"  [{mark}] {r['job_id']}  {r['seconds']:6.1f}s{conv}", file=sys.stderr)

    results = run_all(jobs, runs, work, sector_name, inst.exe, args.timeout,
                      nproc=args.jobs, linelist_dir=args.linelists,
                      resume=args.resume, on_result=_echo)

    doc = write_run_manifest(args.report or (work / 'run_manifest.json'),
                             sector_name, inst, results)
    print(f"[{sector_name}] ok={doc['n_ok']} skipped={doc['n_skipped']} "
          f"failed={doc['n_failed']} not-converged={doc['n_not_converged']}",
          file=sys.stderr)

    #EXITING (1 fail, 0 ok)
    return 1 if doc['n_failed'] else 0