# Author: Enrico Veraldi
# Generate the cloudy input files from the lhs grid generated by gen_lhs_hii.py

import argparse
import pathlib
import re
import shutil
import sys

import h5py
import numpy as np
from jinja2 import StrictUndefined, Template

import galapy.internal.constants as CONST
from galapy.spectroscopy.utils.physics.abundances import format_cloudy_float

#remove possible syntact error in the jinja template (in terms of format)
RESIDUAL_PLACEHOLDER = re.compile(r'\{\{|\}\}|\{%|%\}')

def _decode(v):
    """
    Decodes the input value if it is of type bytes or NumPy generic.
    For bytes, it decodes the value into a string. For NumPy generic,
    it converts the value to its native Python type using `item()`.

    Parameters:
    v : Any
        The value to decode.

    Returns:
    Any
        The decoded value if the input was of type bytes or NumPy generic;
        otherwise, the input value is returned unchanged.
    """
    if isinstance(v, bytes):
        return v.decode()
    if isinstance(v, np.generic):
        return v.item()
    return v

def load_jobs(spec_path):
    """
    Loads job data from an HDF5 file and validates its structure and contents. Return it as
    a list of dictionaries.

    Parameters:
    spec_path: str
        Path to the HDF5 file containing job specifications.

    Raises:
    ValueError
        If any dataset in the file has a different length than the others.
    KeyError
        If the required keys defined in the template are missing from the file.

    Returns:
    list[dict]
        A list of dictionaries representing job data. Each dictionary contains
        key-value pairs decoded from the datasets in the file.
    """
    with h5py.File(spec_path, 'r') as f:
        keys = list (f.keys())
        n = f[keys[0]].shape[0]
        for k in keys:
            if f[k].shape[0] != n:
                raise ValueError(f"{spec_path}: dataset '{k}' has length {f[k].shape[0]}, expected {n}")
        cols = {k: f[k][:] for k in keys}
    missing = set(CONST.TEMPLATE_KEYS_HII) -set (cols)
    if missing:
        raise KeyError(f"{spec_path}: file of jobs does not include {sorted(missing)}")
    return [{k: _decode(cols[k][i]) for k in cols} for i in range(n)]

def render_one(tmpl, job):
    """
    Renders a template with the provided job data, performs strict validation checks, and returns the
    resulting content.

    This function uses the given template and job data to generate output. The jinja template
    is readable in galapy-database

    Parameters:
        tmpl (Template): The template to render the content from.
        job (dict): A dictionary containing job-specific data for rendering the template.

    Returns:
        str: The generated content after successful validation.

    Raises:
        RuntimeError: Raised if any of the following conditions occur:
            - A residual placeholder is detected in the rendered output.
            - A NaN, infinity, or negative infinity is present in the generated output.
            - The "grains" keyword is not properly configured in the output.
    """
    ctx = dict(job)
    for k in CONST.EXP_FIELDS: #in case of exponential fields
        ctx[k] = format_cloudy_float(ctx[k])

    deck = tmpl.render(**ctx)

    # No Residual Placeholder
    m = RESIDUAL_PLACEHOLDER.search(deck)
    if m:
        raise RuntimeError(f"job {job['job_id']}: residual placeholder {deck[max(0, m.start()-30):m.end()+30]!r}")

    # No printed NaN/inf
    if re.search(r'\b(nan|inf|-inf)\b', deck, re.IGNORECASE):
        raise RuntimeError(f"job {job['job_id']}: NaN/inf in the created deck")

    # check grains keyword linear and strictly positive argument in exponential
    grains = [l for l in deck.splitlines() if l.strip().lower().startswith('grains')]
    if len(grains) != 1:
        raise RuntimeError(f"job {job['job_id']}: expected one line grains, found {len(grains)}")
    if 'linear' not in grains[0].lower():
        raise RuntimeError(f"job {job['job_id']}: grains line no keyword linear: {grains[0]!r}")
    if ' log' in grains[0].lower():
        raise RuntimeError(f"job {job['job_id']}: log presented on grains line: {grains[0]!r}")

    return deck

def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('-s','--spec', default="data/grids/hii/hii_grid_spec.h5", help='job spec produced '
                                                                  'by galapy-gen-lhs-hii (default: data/grids/hii/hii_grid_spec.h5)')
    ap.add_argument('-t','--template', default=None, help='template Jinja2 (default: hii.in.j2 from '
                                                          'dataset)')
    ap.add_argument('-d','--sed-dir', default='data/cloudy_seds', help='directory .sed generated via'
                                                                       ' galapy-sed-cloudy-extract')
    ap.add_argument('-o','--out', default="data/hii", help='output directory of .in cloudy '
                                                                 '(default: data/input_hii)')
    ap.add_argument('-l','--limit', type=int, default=None, help='subsample N jobs evenly spread over the grid')
    args = ap.parse_args()

    # check if the user gives a personal template, if he does not, use the default in the database
    if args.template:
        tmpl_path = pathlib.Path(args.template)
    else:
        from galapy.internal.data import DataFile
        from galapy.internal.globs import NEB_TPL_DIR
        tmpl_path = pathlib.Path(DataFile('hii.in.j2', NEB_TPL_DIR).get_file())
    # set output directory
    out_dir = pathlib.Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # instance of jinja2 template
    tmpl = Template(tmpl_path.read_text(), undefined=StrictUndefined,
                    keep_trailing_newline=True)

    # jobs list, in case of limit imposed, run not all grid but a subsample (for testing)
    jobs = load_jobs(args.spec)
    if args.limit and args.limit < len(jobs):
        jobs = [jobs[i] for i in
                np.linspace(0, len(jobs) - 1, args.limit).round().astype(int)]

    # rendering deck, accumulate seds in set (no duplicates)
    sed_dir = pathlib.Path(args.sed_dir)
    seds_needed = set()
    for job in jobs:
        deck_path = out_dir / f"hii_{job['job_id']}.in"
        deck_path.write_text(render_one(tmpl, job))
        seds_needed.add(job['sed_file'])

    # staging, validation and copy of SEDs
    sed_out = out_dir / 'SED'
    sed_out.mkdir(exist_ok=True)
    for s in sorted(seds_needed):
        src = sed_dir / s
        if not src.exists():
            raise FileNotFoundError(f"SED missing: {src}. Re run galapy-sed-cloudy-extract")
        shutil.copy2(src, sed_out / s)

    # generate manifest of the input runs in jobs.txt
    (out_dir / 'jobs_hii.txt').write_text(
        '\n'.join(j['job_id'] for j in jobs) + '\n')

    print(f"[gen_input] {len(jobs)} deck -> {out_dir}", file=sys.stderr)
    print(f"[gen_input] {len(seds_needed)} SED -> {sed_out}", file=sys.stderr)

if __name__ == '__main__':
    main()










